apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-pedecatalogo
spec:
  selector:
    matchLabels:
      app: api-pedecatalogo
  template:
    metadata:
      labels:
        app: api-pedecatalogo
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd            
      containers:
      - name: api-pedecatalogo
        image: leonardosantos88/api-produto:v1
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 443
          name: https
        imagePullPolicy: Always
        env:
        - name: MONGODB_URI
          value: mongodb://mongouser:s3v3n14@mongo-service-app:27020/admin
