apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployapi-conversao2023loadbalancer
spec:
  selector:
    matchLabels:
      app: api-conversao2023-LoadBalancer
      app: loadbalancer
  template:
    metadata:
      labels:
        app: api-conversao2023-LoadBalancer
        app: loadbalancer
    spec:
      containers:
      - name: apiconversao-services
        image: kubedevio/api-conversao:v1-machine-name

