apiVersion: v1
kind: Service
metadata:
  name: svc-api-conversao2023loadbalancer
spec:
  selector:
    app: api-conversao2023-LoadBalancer
    app: loadbalancer
  ports:
  - port: 30005
    targetPort: 8080
  type: LoadBalancer
