apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment-app
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd          
      containers:
      - name: mongodb
        image: mongo:4.2.8
        ports:
        - containerPort: 27020
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "mongouser"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "s3v3n14"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service-app
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27020
      targetPort: 27020