apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-pedecatalogo
spec:
  selector:
    matchLabels:
      app: api-pedecatalogo
  template:
    metadata:
      labels:
        app: api-pedecatalogo
    spec:
      containers:
      - name: api-pedecatalogo
        image: leonardosantos88/api-catalogo:v1
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        imagePullPolicy: Always
        env:
        - name: Mongo__Host
          value: mongo-service-app
        - name: Mongo__User
          value: mongouser
        - name: Mongo_Password
          value: mongopwd
        - name: Mongo__Port
          value: "27017"
        - name: Mongo__DataBase
          value: admin