apiVersion: v1
kind: Service
metadata:
  name: api-service-app
spec:
  selector:
    app: api-pedecatalogo
  ports:
  - port: 80
    targetPort: 80
    name: http
    nodePort: 30007
  - port: 443
    targetPort: 443
    name: https
    nodePort: 30008
    
  type: NodePort
