apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploygreen
  namespace: green
spec:
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - name: blueapp
        image: kubedevio/nginx-color:green
      