apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployblue
  namespace: blue
spec:
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: blueapp
        image: kubedevio/nginx-color:blue
      