apiVersion: apps/v1
kind: Deployment
metadata:
  name: meuprimeirodeployment2023
spec:
  selector:
    matchLabels:
      app: exemplo
  template:
    metadata:
      labels:
        app: exemplo
    spec:
      containers:
      - name: meucontainerdeploy2023
        image: kubedevio/nginx-color:green
        